name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - v**
    tags:
      - "v**"

jobs:
  source:
    name: Source Verification
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Verifying source code
        run: make check

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "8808211+pilardi@users.noreply.github.com"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: 3.11
      - name: Running unit tests
        run: make tests
      - name: Running integration tests
        run: make tests/dist/git-llm-utils
      - name: Generate Artifact Name
        run: |
          ARTIFACT_NAME="git-llm-utils-${{ runner.os || matrix.os }}-${{ runner.arch || 'default' }}" &&
          ARTIFACT="dist/${ARTIFACT_NAME,,}" &&
          mv dist/git-llm-utils ${ARTIFACT} &&
          echo "ARTIFACT=${ARTIFACT}" >> $GITHUB_ENV &&
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
      - name: Uploading Build Artifacts
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          compression-level: 7
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT }}
      - name: Uploading Release Artifacts
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARTIFACT }}

