name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - v**
    tags:
      - "v**"

permissions:
  contents: write # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release

jobs:
  verify:
    name: Source Verification
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Verifying source code
        run: make check

  build:
    needs: verify
    name: Build
    if: github.ref_type != 'tag'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "8808211+pilardi@users.noreply.github.com"
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
      - name: Build
        run: make dist/git-llm-utils
      - name: Run unit tests
        run: make tests
      - name: Run integration tests
        run: make tests/dist/git-llm-utils
      - name: Prepare Artifacts
        uses: ./.github/actions/artifacts
        with:
          os: ${{ runner.os || matrix.os }}
          arch: ${{ runner.arch || 'default' }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT }}

  release:
    name: Release
    if: github.ref_type == 'tag'
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-latest ]
        python: [3.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
      - name: Build
        run: make dist/git-llm-utils
      - name: Prepare Artifacts
        uses: ./.github/actions/artifacts
        with:
          os: ${{ runner.os || matrix.os }}
          arch: ${{ runner.arch || 'default' }}
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARTIFACT }}
